require 'rails_helper'

RSpec.describe User, type: :model do
  it "should fail (user with no password)" do
    @user = User.create(email: "user@example.com", password: "password")
    expect(@user.email).to eq("user@example.com")
  end
end

# Untested LOC (generated by coverage)
# :database_authenticatable, :registerable,
# :recoverable, :rememberable, :validatable

# before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]