require 'rails_helper'

RSpec.describe User, type: :model do
  pending "add some examples to (or delete) #{__FILE__}"
end


# Untested LOC (generated by coverage)
# :database_authenticatable, :registerable,
# :recoverable, :rememberable, :validatable

# before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
